[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "space_invaders"
version = "0.1.0"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib",
]
